#!/usr/bin/env bash

# Function to display usage
usage() {
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
}

# Check if the number of parameters is less than 4
if [ $# -lt 4 ]; then
    usage
fi

# Assigning parameters to variables
PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

# Transfer file using scp
scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP:~/"

# Check if scp command was successful
if [ $? -eq 0 ]; then
    echo "File transferred successfully"
else
    echo "File transfer failed"
fi
