#!/usr/bin/env bash
# installs nginx, configures it to listen on port 80, serve "Hello World!" at its root,
# set up a 301 redirect from /redirect_me, and configure a custom 404 page

# Update package lists
sudo apt-get update -y

# Install nginx
sudo apt-get install nginx -y

# Create the index.html file with "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index.html

# Create the 404.html file with custom content
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Update Nginx configuration to point to the /var/www/html directory and add redirect and custom 404 page
sudo bash -c 'cat > /etc/nginx/sites-available/default << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
EOF'

# Start nginx without using systemctl
sudo service nginx start

# Ensure nginx is set to start on boot
sudo update-rc.d nginx defaults

# Check if Nginx is running, and start or restart the service accordingly
if ! pgrep nginx > /dev/null; then
    sudo service nginx start
else
    sudo service nginx restart
fi

# Display message to indicate script has finished running
echo "Nginx installation and configuration with redirect and custom 404 page completed."

HOSTNAME=$(hostname)

# Add custom HTTP header to Nginx configuration
sudo sed -i "/http {/a \\    add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf

# Restart Nginx to apply changes
sudo service nginx restart
