#!/usr/bin/env bash
# Ignore SC2154 for shellcheck

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Get the hostname
HOSTNAME=$(hostname)

# Add custom HTTP header to Nginx configuration
sudo sed -i "/http {/a \\    add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf

# Restart Nginx to apply changes
sudo systemctl restart nginx
