#!/usr/bin/env bash
# This script configures HAProxy on a new Ubuntu machine

# Update package list and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
    listen load_balancer
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 27517-web-01 54.89.182.131:80 check
    server 27517-web-02 52.91.184.48:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
