#!/usr/bin/env bash
sudo apt update
sudo apt install -y nginx
sudo service nginx start
sudo sed -i 's/listen 80 default_server;/listen 80 default_server;/' /etc/nginx/sites-available/default
sudo service nginx restart
