#!/usr/bin/env bash
# This script creates a .pid file and deletes the file and terminates
# itself when receiving a SIGQUIT or SIGTERM signal
# shellcheck disable=SC2009
function hate_kill()
{
	echo "I hate the kill command"
	rm -f /var/run/myscript.pid
}

function no_love()
{
	echo "Y U no love me?!"
	rm -f /var/run/myscript.pid
}

trap hate_kill SIGTERM
trap no_love SIGINT

pgrep -f 100-process_and_pid_file >> /var/run/myscript.pid
while :
do
	echo "To infinity and beyond"
	sleep 2
done
