#!/usr/bin/env bash
# This script that manages manage_my_process script
# shellcheck disable=SC2009
if [ "$1" = "start" ]; then
	./manage_my_process &
	echo $! >> /var/run/my_process.pid
	echo "manage_my_process started"
elif [ "$1" = "stop" ]; then
	xargs kill < "/var/run/my_process.pid"
	rm -f /var/run/my_process.pid
	echo "manage_my_process stopped"
elif [ "$1" = "restart" ]; then
	xargs kill < "/var/run/my_process.pid"
	rm -f /var/run/my_process.pid
	./manage_my_process &
	echo $! >> /var/run/my_process.pid
	echo "manage_my_process restarted"

else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
