#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely
# and "I am invincible!!!" when receiving SIGTERM
# shellcheck disable=SC2009
trap "echo I am invincible!!!" SIGTERM
while :
do
	echo "To infinity and beyond"
	sleep 2
done
