#!/usr/bin/env bash
# This script reads the content of '/etc/passwd'
# and displays the username, userid and user home directory path
FILENAME="/etc/passwd"
while IFS=: read -r username password uid gid comment homedir cmd
do
	echo "The user $username is part of the $gid gang, lives in $homedir and rides $cmd. $uid's place is protected by the passcode $password, more info about the user here: $comment"
done < $FILENAME
