#!/usr/bin/env bash
# This script displays 'Best School' 10 times
i=0
while [ $i -lt 10 ]
do
((i++))
if [[ $i -eq 4 ]]
then
	echo "bad luck"
	continue
elif [[ $i -eq 8 ]]
then
	echo "good luck"
	continue
else
	echo "Best School"
fi
done
