#!/usr/bin/env bash
# This script displays 'Best School' 10 times
i=0
while [ $i -lt 20 ]
do
((i++))
case $i in
	4)
		echo $i
		echo "bad luck from China";;
	9)
		echo $i
		echo "bad luck from Japan";;
	17)
		echo $i
		echo "bad luck from Italy";;
	*)
		echo $i;;
esac
done
