#!/bin/bash

# Script that configures an Ubuntu server
# sudo cp /etc/hosts ~/hosts.old
# sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.old
# echo "8.8.8.8	facebook.com" >> ~/hosts.old
# sudo cp -f ~/hosts.old /etc/hosts


# Backup the original /etc/hosts file
sudo cp /etc/hosts /etc/hosts.backup

# Update the /etc/hosts file
sudo sed -i '/127.0.0.1\s\+localhost/d' /etc/hosts
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

echo "Configuration complete."
