#!/usr/bin/env bash

# Script that configures an Ubuntu server
sudo cp /etc/hosts ~/hosts.old
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.old
echo "8.8.8.8	facebook.com" >> ~/hosts.old
sudo cp -f ~/hosts.old /etc/hosts

