#!/usr/bin/env bash
# Configure Nginx to run as nginx user and listen on port 8080
sudo apt-get update
sudo apt-get install -y nginx
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
sudo useradd -r -d /nonexistent -s /bin/false nginx || true
sudo service nginx restart
