#!/usr/bin/env bash
# Create an RSA key pair

# Define the key name, number of bits, and passphrase
KEY_NAME=school
BITS=4096
PASSPHRASE=betty

# Generate the RSA key pair
ssh-keygen -t rsa -b $BITS -f $KEY_NAME -N $PASSPHRASE
